name: Frontend build&test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - run: echo $(pwd)
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'npm'
        cache-dependency-path: /home/runner/work/wschool/wschool/frontend/package-lock.json

    - run: npm i
      working-directory: frontend/
    - run: npm run build --if-present
      working-directory: frontend/
    - run: npm test
      working-directory: measurements_frontend/measurements
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H:%M')"
    - name: Get current tag
      id: tag
      run: echo "::set-output name=tag::$(date +'%Y.%m.%d.%H.%M')"
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: Frontend-Nightly-${{ steps.date.outputs.date }}
        tag_name: frontend_nightly.${{ steps.tag.outputs.tag }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: zip build
      run: zip -r artifact.zip build
      working-directory: frontend/
    - name: upload artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./measurements_frontend/measurements/artifact.zip
        asset_name: Frontend-Nightly-${{ steps.date.outputs.date }}.zip
        asset_content_type: application/zip
